"""前端契约与去伪造数据的静态门禁（B4 验收项的可执行化）。

背景：B4 的两条验收标准原先靠人工 grep——「全仓无第二份手抄契约」与「前端无硬编码
置信度表 / 无正则解析工具结果」；人工复查会随迭代失效，这里固化成门禁（与
`tests/test_architecture.py` 同属静态检查，离线、不触网）。

验证：
- `frontend/src/api/generated.ts` 是契约生成物（components/operations/text/event-stream 齐备）；
- 前端不再有第二份手抄契约（DecisionCard / SSE 事件 interface）；
- api 层契约类型从生成物派生（components[...] / operations[...]）；
- 已删除的伪造数据辅助不得回归（confidenceMath / verdictFrom / parseTime / SessionPayload）；
- D3Page 用卡片真实字段（verdict / confidence_detail），旧常量表魔数不回归；
- D2Page 读 tool_result 的结构化 data，且不再对工具摘要做正则解析。
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FRONTEND_SRC = ROOT / "frontend" / "src"
GENERATED = FRONTEND_SRC / "api" / "generated.ts"

# 已删除的伪造数据 / 手抄契约辅助（回归即失败）
_FORBIDDEN_SYMBOLS = ("confidenceMath", "verdictFrom", "parseTime", "SessionPayload", "SSEEventBase")
# 旧置信度常量表的魔数写法（B4-3 删除）
_FORBIDDEN_CONFIDENCE_RETURNS = ("return 78", "return 58", "return 34")
# 契约类型的手抄形态（生成物之外不得再声明）
_HANDWRITTEN_CONTRACT = (
    re.compile(r"interface\s+DecisionCard\b"),
    re.compile(r"interface\s+(?:Queued|Step|ToolCall|ToolResult|Token|Card|Error|Done)Event\b"),
)


def _sources() -> list[Path]:
    """前端源码文件（.ts/.tsx，排除生成物）。"""
    files = sorted(FRONTEND_SRC.rglob("*.ts")) + sorted(FRONTEND_SRC.rglob("*.tsx"))
    return [path for path in files if path.resolve() != GENERATED.resolve()]


def test_generated_contract_is_present() -> None:
    """generated.ts 是 openapi-typescript 生成物，覆盖 SSE 与决策卡契约。"""
    text = GENERATED.read_text(encoding="utf-8")
    assert "auto-generated by openapi-typescript" in text
    assert "export interface components" in text
    assert "export interface operations" in text
    assert '"text/event-stream"' in text  # SSE 端点响应契约
    assert "ConfidenceDetail" in text and "DecisionCard" in text


def test_no_second_handwritten_contract() -> None:
    """前端不得再有第二份手抄契约（DecisionCard / SSE 事件 interface）。"""
    offenders = [
        f"{path.relative_to(ROOT)}: {pattern.pattern}"
        for path in _sources()
        for pattern in _HANDWRITTEN_CONTRACT
        if pattern.search(path.read_text(encoding="utf-8"))
    ]
    assert offenders == []


def test_contract_types_derive_from_generated() -> None:
    """api 层契约类型从生成物派生（components[...] / operations[...]）。"""
    events = (FRONTEND_SRC / "api" / "events.ts").read_text(encoding="utf-8")
    assert 'from "./generated"' in events
    assert 'components["schemas"]["DecisionCard"]' in events
    assert 'operations["' in events and '"text/event-stream"' in events


def test_fabricated_data_helpers_do_not_come_back() -> None:
    """已删除的伪造数据辅助不得回归（B4-3/B4-4 验收项）。"""
    offenders = [
        f"{path.relative_to(ROOT)}: {symbol}"
        for path in _sources()
        for symbol in _FORBIDDEN_SYMBOLS
        if symbol in path.read_text(encoding="utf-8")
    ]
    assert offenders == []


def test_d3page_uses_real_card_fields() -> None:
    """D3Page 读卡片真实字段（verdict / confidence_detail），旧常量表不回归。"""
    text = (FRONTEND_SRC / "pages" / "D3Page.tsx").read_text(encoding="utf-8")
    assert "card?.verdict" in text
    assert "confidence_detail" in text
    offenders = [item for item in _FORBIDDEN_CONFIDENCE_RETURNS if item in text]
    assert offenders == []


def test_d2page_consumes_structured_tool_data() -> None:
    """D2Page 读 tool_result.data；不再对工具摘要做正则解析。"""
    text = (FRONTEND_SRC / "pages" / "D2Page.tsx").read_text(encoding="utf-8")
    assert "event.data" in text and "data[" in text
    assert ".match(" not in text
    assert "new RegExp(" not in text