/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 自由对话（ReAct），SSE 流式事件
         * @description 接收消息 → queued → ReAct 过程事件（工具）→ token → done。
         */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 决策管线（D1–D3），SSE 事件直至决策卡片
         * @description 一句话 → 管线步骤/工具事件逐条推 → 末端 card + done。
         */
        post: operations["decide_api_decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 照片复盘（D4），上传图片 → SSE 事件至复盘卡片
         * @description 上传照片 → 复盘管线（多模态分析）→ 复盘卡 → done。
         *
         *     临时文件由流内 worker 线程自建自销（**不能**在端点里建删）：SSE 流是惰性的，
         *     端点在返回响应时流还没被消费，若那时删文件，worker 读图必 FileNotFoundError
         *     （D4 真实联调实测「图片读取失败」，见 tests/test_api.py 的竞态回归用例）。
         */
        post: operations["photos_review_api_photos_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读取用户档案（M1.1-01）
         * @description 返回当前档案（camera_body/lenses/preferences/…）。
         */
        get: operations["get_profile_api_profile_get"];
        /**
         * 更新用户档案（M1.1-01，显式写入）
         * @description 部分更新档案：只更新出现字段，未知字段忽略。
         */
        put: operations["put_profile_api_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 会话历史与 TraceReport 回放
         * @description 返回会话记录（历史 + 工作区）与最近一次运行的 TraceReport。
         */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_photos_review_api_photos_review_post */
        Body_photos_review_api_photos_review_post: {
            /**
             * File
             * @description 照片（jpg/png，≤10MB）
             */
            file: string;
            /**
             * Focus
             * @description 分析重点，如「构图」
             * @default
             */
            focus: string;
            /**
             * Plan Reference
             * @description 历史计划（DecisionCard JSON 或文本，可空）
             * @default
             */
            plan_reference: string;
            /**
             * Session Id
             * @description 会话标识；缺省自动新建
             * @default
             */
            session_id: string;
        };
        /**
         * CardEvent
         * @description 决策卡片事件（管线末端产物）。
         */
        CardEvent: {
            card: components["schemas"]["DecisionCard"];
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "card";
        };
        /**
         * ChatRequest
         * @description 自由对话请求（ReAct）：message + 可选 session_id。
         */
        ChatRequest: {
            /**
             * Message
             * @description 用户消息文本
             */
            message: string;
            /**
             * Session Id
             * @description 会话标识；缺省自动新建
             * @default
             */
            session_id: string;
        };
        /**
         * ConfidenceDetail
         * @description 置信度明细：主值 + 区间 + 依据构成（**规则推导，非概率估计**）。
         *
         *     由 infra/confidence.confidence_detail() 依据 evidence 的来源级别加权推导；
         *     契约层只承载字段，不含推导规则。前端铁律①（主值 + 区间条 + 依据）直接渲染本对象。
         *
         *     Attributes:
         *         level: 卡片整体等级（high / medium / low），沿用模型给出的等级标注。
         *         score: 置信度主值（0–100，依据级别加权平均）。
         *         low: 区间下限（0–100）。
         *         high: 区间上限（0–100）。
         *         basis: 推导依据说明（人话，供「依据」小字展示）。
         *         high_count: 依据中 high 级来源条数。
         *         medium_count: 依据中 medium 级来源条数。
         *         low_count: 依据中 low 级来源条数。
         */
        ConfidenceDetail: {
            /**
             * Basis
             * @default
             */
            basis: string;
            /**
             * High
             * @default 0
             */
            high: number;
            /**
             * High Count
             * @default 0
             */
            high_count: number;
            /**
             * Level
             * @default low
             */
            level: string;
            /**
             * Low
             * @default 0
             */
            low: number;
            /**
             * Low Count
             * @default 0
             */
            low_count: number;
            /**
             * Medium Count
             * @default 0
             */
            medium_count: number;
            /**
             * Score
             * @default 0
             */
            score: number;
        };
        /**
         * DecideRequest
         * @description 决策管线请求（D1–D3）：一句话 + 可选 session_id。
         */
        DecideRequest: {
            /**
             * Request
             * @description 决策请求（一句话）
             */
            request: string;
            /**
             * Session Id
             * @description 会话标识；缺省自动新建
             * @default
             */
            session_id: string;
        };
        /**
         * DecisionCard
         * @description 决策卡片：管线的最终结构化输出（M2 结构性必填 evidence / confidence）。
         *
         *     Attributes:
         *         conclusion: 结论（一句话「该不该出门 / 几点去 / 去哪 / 带什么」）。
         *         evidence: 依据列表（必填；即使为空也要输出显式 []，防 M2 落空）。
         *         confidence: 整体置信度（high / medium / low；必填）。
         *         verdict: 三态结论（go 值得去 / wait 再观察 / risk 不建议专程；未知为空串）。
         *             由模型按提示词给出，前端直接读字段，不做中文正则猜测（B4-3）。
         *         confidence_detail: 置信度明细（代码规则推导，B4-3 起随卡片下发；缺省为 None）。
         *         time_window: 建议时间窗口文案（如「05:10-05:40，黄金 05:20-06:10」）。
         *         locations: 推荐机位列表。
         *         params: 参数建议列表。
         *         alternatives: 备选方案文案列表。
         *         degraded: 降级原因（配额 / 管线降级标注，空串表示未降级）。
         */
        DecisionCard: {
            /** Alternatives */
            alternatives?: string[];
            /** Conclusion */
            conclusion: string;
            /** Confidence */
            confidence: string;
            confidence_detail?: components["schemas"]["ConfidenceDetail"] | null;
            /**
             * Degraded
             * @default
             */
            degraded: string;
            /** Evidence */
            evidence: components["schemas"]["Source"][];
            /** Locations */
            locations?: components["schemas"]["LocationSuggestion"][];
            /** Params */
            params?: components["schemas"]["ParamSuggestion"][];
            /**
             * Time Window
             * @default
             */
            time_window: string;
            /**
             * Verdict
             * @default
             */
            verdict: string;
        };
        /**
         * DoneEvent
         * @description 结束事件（事件流终止标记）。
         */
        DoneEvent: {
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "done";
        };
        /**
         * ErrorEvent
         * @description 错误事件（单请求失败不中断流，随后必有 done）。
         */
        ErrorEvent: {
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LocationSuggestion
         * @description 一个推荐机位（含理由）。
         */
        LocationSuggestion: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /**
         * ParamSuggestion
         * @description 一条拍摄参数建议（含理由）。
         */
        ParamSuggestion: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Value
             * @default
             */
            value: string;
        };
        /**
         * ProfilePayload
         * @description 档案编辑（M1.1-01）：全部字段可选，PUT 只更新出现的字段。
         */
        ProfilePayload: {
            /** Camera Body */
            camera_body?: string | null;
            /** Common Locations */
            common_locations?: string[] | null;
            /** Favorite Spots */
            favorite_spots?: {
                [key: string]: unknown;
            }[] | null;
            /** Lenses */
            lenses?: string[] | null;
            /** Preferences */
            preferences?: string[] | null;
            /** Skill Level */
            skill_level?: string | null;
        };
        /**
         * QueuedEvent
         * @description 排队事件：告知当前 LLM 队列位置。
         */
        QueuedEvent: {
            /**
             * Position
             * @default 1
             */
            position: number;
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "queued";
        };
        /**
         * Source
         * @description 一条决策依据（M2）：哪个工具 / 哪个字段 / 置信度 / 说明。
         */
        Source: {
            /**
             * Confidence
             * @default low
             */
            confidence: string;
            /**
             * Field
             * @default
             */
            field: string;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Tool
             * @default
             */
            tool: string;
        };
        /**
         * StepEvent
         * @description 管线步骤事件（trace step 的协议形态）。
         */
        StepEvent: {
            /**
             * Input Summary
             * @default
             */
            input_summary: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Output Summary
             * @default
             */
            output_summary: string;
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Ts
             * @default
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "step";
        };
        /**
         * TokenEvent
         * @description 正文事件（当前按「每轮完整文本」发送，逐 token 流式留待 streaming 通道）。
         */
        TokenEvent: {
            /**
             * Content
             * @default
             */
            content: string;
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "token";
        };
        /**
         * ToolCallEvent
         * @description 工具调用事件（trace tool 拆成 call / result 两条）。
         */
        ToolCallEvent: {
            /**
             * Arguments
             * @default
             */
            arguments: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Ts
             * @default
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool_call";
        };
        /**
         * ToolResultEvent
         * @description 工具结果事件：摘要文本 + **结构化结果**（前端直接消费字段，不做正则解析）。
         *
         *     Attributes:
         *         result: 人类可读摘要（截断，供轨迹面板展示）。
         *         data: 工具返回的结构化 dict（JSON 可解析时提供，否则缺省）；前端按真实字段
         *             读取（如 sun_times 的「日出」），不再对摘要文本做正则解析（B4-4）。
         */
        ToolResultEvent: {
            /**
             * Confidence
             * @default low
             */
            confidence: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
            /**
             * Data Source
             * @default
             */
            data_source: string;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
            /**
             * Field
             * @default
             */
            field: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Result
             * @default
             */
            result: string;
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Ts
             * @default
             */
            ts: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool_result";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description SSE 事件流（event: <type> + data: JSON） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["QueuedEvent"] | components["schemas"]["StepEvent"] | components["schemas"]["ToolCallEvent"] | components["schemas"]["ToolResultEvent"] | components["schemas"]["TokenEvent"] | components["schemas"]["CardEvent"] | components["schemas"]["ErrorEvent"] | components["schemas"]["DoneEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_decide_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideRequest"];
            };
        };
        responses: {
            /** @description SSE 事件流（event: <type> + data: JSON） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["QueuedEvent"] | components["schemas"]["StepEvent"] | components["schemas"]["ToolCallEvent"] | components["schemas"]["ToolResultEvent"] | components["schemas"]["TokenEvent"] | components["schemas"]["CardEvent"] | components["schemas"]["ErrorEvent"] | components["schemas"]["DoneEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    photos_review_api_photos_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_photos_review_api_photos_review_post"];
            };
        };
        responses: {
            /** @description SSE 事件流（event: <type> + data: JSON） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["QueuedEvent"] | components["schemas"]["StepEvent"] | components["schemas"]["ToolCallEvent"] | components["schemas"]["ToolResultEvent"] | components["schemas"]["TokenEvent"] | components["schemas"]["CardEvent"] | components["schemas"]["ErrorEvent"] | components["schemas"]["DoneEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilePayload"];
                };
            };
        };
    };
    put_profile_api_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilePayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
